version: '3.7'

#services:
#  ioServer:
#    image: quay.io/minio/minio
#    command: server /data --console-address ":9008"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3
#    ports:
#      - "9000:9000"
#      - "9008:9008"
#    environment:
#      MINIO_ROOT_USER : "AKIAIOSFODNN7EXAMPLE"
#      MINIO_ROOT_PASSWORD : "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
##    volumes:
##      -  /portable/minio/data:/data
#    restart: unless-stopped
