name: Build&Push Docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wareagledocker/eagle-io:latest
          file: docker/Dockerfile-EagleIO
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
#      -
#        name: Docker Hub Description
#        uses: peter-evans/dockerhub-description@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          repository: wareagledocker/eagle-io
#          readme-filepath: server/README.md
